config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
  end

  def create
    @cocktail = Cocktail.new(name: params["cocktail"]["name"])
    @cocktail.save
    @cocktail_dose = Cocktail.last
    redirect_to new_cocktail_dose_path(@cocktail_dose)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @ingredients = Ingredient.all
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @dose.cocktail_id = @cocktail.id
  end

  def create
    @dose = Dose.new(params_dose)
    @dose.save!
  end

  private

  def params_dose
    params.require(:dose).permit(:cocktail_id, :ingredient_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="navbar-lewagon">
   <p>T'es là pour boire, je vais t'aider!</p>
  <div>
   <%= image_tag "la_joconde.jpg", alt: "La joconde", class:"avatar"%>
  </div>
</div>
<h1>Cocktailssssssssssssssss</h1>
<div class="ajout">
  <h2>Ajoute ton cocktail créateur fou</h2>
  <%= simple_form_for [@cocktail] do |f| %>
    <%= f.input :name %>
    <%= f.submit "add", class: "btn btn-primary" %>
  <% end %>
</div>
<div class="container">
  <div class="wrapper">
    <% @cocktails.each do |cocktail| %>
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"> <%= link_to cocktail.name, cocktail_path(cocktail)%> </h5>
          <!-- ici mettre d'autre carac et photo -->
          <% cocktail.doses.each do |dose| %>
            <p> <%= dose.ingredient.name %>: <%= dose.description %> </p>
          <% end %>
        </div>
      </div>
    <% end  %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="button-central">
      <%= link_to 'crée ton cocktail', cocktails_path() , method: :post%>
  </div>

  <div class="wrapper">
    <% @ingredients.each do |ingredient| %>
      <div class="card-ingredient" style="width: 18rem;">
        <%= image_tag "cocktail.png", alt: ingredient.name, class:"card-img-top"%>
        <div class="card-body">
          <h5 class="card-title"> <p><%= ingredient.name %></p> </h5>
        </div>
        <%= simple_form_for [@cocktail_dose, @dose] do |f| %>
          <%= f.input :description %>
          <%= f.submit "add", class: "btn btn-primary" %>
        <% end %>
      </div>
    <% end  %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="navbar-lewagon">
   <p> <%= link_to 'retour to cocktail', cocktails_path %> </p>
  <div>
    <%= image_tag "la_joconde.jpg", alt: "La joconde", class:"avatar"%>
  </div>
</div>

<div class="card" style="width: 100%;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"> <%= @cocktail.name %> </h5>
    <% @cocktail.doses.each do |dose| %>
        <p> <%= dose.ingredient.name %>: <%= dose.description %> </p>
    <% end %>
    <h5><%= link_to '+', new_cocktail_dose_path(@cocktail) %></h2>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="button-central">
      <%= link_to 'crée ton cocktail', cocktail_path(@cocktail)%>
  </div>

  <div class="wrapper">
    <% @ingredients.each do |ingredient| %>
      <div class="card-ingredient" style="width: 18rem;">
        <%= image_tag "cocktail.png", alt: ingredient.name, class:"card-img-top"%>
        <div class="card-body">
          <h5 class="card-title"> <p><%= ingredient.name %></p> </h5>
        </div>
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%=  f.hidden_field :cocktail_id, :value => @cocktail.id %>
          <%=  f.hidden_field :ingredient_id, :value => ingredient.id %>
          <%= f.input :description %>
          <%= f.submit "add", class: "btn btn-primary" %>
        <% end %>
      </div>
    <% end  %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script:500,700|Modak&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script type="text/javascript">
      // Get parameters from edit boxes and configure mouse trail
      let getp = () => {
        // Get parameters
        let f= document.forms["frm"];
        bubbletrail.size= parseInt(f.bbsize.value);
        bubbletrail.jitter= parseInt(f.bbjitter.value);
        bubbletrail.zindex= parseInt(f.bbzindex.value);
        bubbletrail.life= parseInt(f.bblife.value);
      }
      // Set parameters in edit boxes
      let setp = (size, jitter, zindex, life) => {
        let f= document.forms["frm"];
        f.bbsize.value= size;
        f.bbjitter.value= jitter;
        f.bbzindex.value= zindex;
        f.bblife.value= life;
      }
      // Show initial values
      setp(bubbletrail.size, bubbletrail.jitter, bubbletrail.zindex, bubbletrail.life);
    </script>

    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>